### ISSUE TITLE
Masstree's pointer index in minipage doesn't match

### ISSUE THREAD

**Issue by wangtzh** [hkimura/foedus_code#80] opened 2015-07-29 18:09 UTC
Failing assertion: 
"pointer_index == minipage.find_pointer(searching_slice)" in adopt_from_child(): foedus-core/src/foedus/storage/masstree/masstree_page_impl.cpp:1300

Setting metadata's min_layer_hint_ to higher value (currently 1) seems working for now.

**Comment by hkimura** [comment] 2015-07-29 20:14
Full backtrace appreciated.
If you can attach debugger, could you also paste McsBlock values of the page lock?
As we chatted, I'm suspecting 1) bogus write from random place, and 2) bug in lock.
In either case, we might find something interesting in McsBlock and other page headers.

I observed a similar error, though in different place, that only happens in dragonhawk and release mode. Can you make a shorter testcase to reproduce? Something like a testcase that very frequently triggers next-layer transfer and page split/rebalace etc?

**Comment by wangtzh** [comment] 2015-07-30 22:46
See below a full backtrace (happened in read()); trying to reproduce it in a simpler test case.

- [0/16] in foedus::print_backtrace() : foedus-core/libfoedus-core.so(_ZN6foedus15print_backtraceEv+0x28) [0x7fe51285d9c0] (libbacktrace: [0x7FE51285D9BF])
- [1/16] in foedus::print_assert_backtrace(char const*, char const*, int, char const*) : foedus-core/libfoedus-core.so(_ZN6foedus22print_assert_backtraceEPKcS1_iS1_+0x42) [0x7fe51285dbb6] (libbacktrace: [0x7FE51285DBB5])
- [2/16] in foedus::storage::masstree::MasstreeIntermediatePage::adopt_from_child(foedus::thread::Thread*, unsigned long, unsigned char, unsigned char, foedus::storage::masstree::MasstreePage*) : foedus-core/libfoedus-core.so(_ZN6foedus7storage8masstree24MasstreeIntermediatePage16adopt_from_childEPNS_6thread6ThreadEmhhPNS1_12MasstreePageE+0x1a91) [0x7fe51272c915] (libbacktrace: [0x7FE51272C914])
- [3/16] in foedus::storage::masstree::MasstreeStoragePimpl::locate_record(foedus::thread::Thread*, void const*, unsigned short, bool, foedus::storage::masstree::MasstreeBorderPage**, unsigned short*, foedus::xct::XctId*) : foedus-core/libfoedus-core.so(_ZN6foedus7storage8masstree20MasstreeStoragePimpl13locate_recordEPNS_6thread6ThreadEPKvtbPPNS1_18MasstreeBorderPageEPtPNS_3xct5XctIdE+0xc73) [0x7fe512758b01] (libbacktrace: [0x7FE512758B00])
- [4/16] in foedus::storage::masstree::MasstreeStorage::get_record(foedus::thread::Thread*, void const*, unsigned short, void*, unsigned short*) : foedus-core/libfoedus-core.so(_ZN6foedus7storage8masstree15MasstreeStorage10get_recordEPNS_6thread6ThreadEPKvtPvPt+0xc7) [0x7fe512744df7] (libbacktrace: [0x7FE512744DF6])
- [5/16] in foedus::ycsb::YcsbClientTask::do_read(foedus::ycsb::YcsbKey const&) : ./ycsb_masstree(_ZN6foedus4ycsb14YcsbClientTask7do_readERKNS0_7YcsbKeyE+0x96) [0x426488] (libbacktrace: [0x426487])
- [6/16] in foedus::ycsb::YcsbClientTask::run(foedus::thread::Thread*) : ./ycsb_masstree(_ZN6foedus4ycsb14YcsbClientTask3runEPNS_6thread6ThreadE+0x566) [0x425f10] (libbacktrace: [0x425F0F])
- [7/16] in foedus::ycsb::ycsb_client_task(foedus::proc::ProcArguments const&) : ./ycsb_masstree(_ZN6foedus4ycsb16ycsb_client_taskERKNS_4proc13ProcArgumentsE+0x109) [0x425871] (libbacktrace: [0x425870])
- [8/16] in foedus::thread::ThreadPimpl::handle_tasks() : foedus-core/libfoedus-core.so(_ZN6foedus6thread11ThreadPimpl12handle_tasksEv+0x786) [0x7fe51283e2d6] (libbacktrace: [0x7FE51283E2D5])
- [9/16] in void std::_Mem_fn<void (foedus::thread::ThreadPimpl::*)()>::operator()<, void>(foedus::thread::ThreadPimpl*) const : foedus-core/libfoedus-core.so(_ZNKSt7_Mem_fnIMN6foedus6thread11ThreadPimplEFvvEEclIIEvEEvPS2_DpOT_+0x65) [0x7fe512846d11] (libbacktrace: [0x7FE512846D10])
- [10/16] in void std::_Bind_simple<std::_Mem_fn<void (foedus::thread::ThreadPimpl::*)()> (foedus::thread::ThreadPimpl*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) : foedus-core/libfoedus-core.so(_ZNSt12_Bind_simpleIFSt7_Mem_fnIMN6foedus6thread11ThreadPimplEFvvEEPS3_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE+0x43) [0x7fe512846c61] (libbacktrace: [0x7FE512846C60])
- [11/16] in std::_Bind_simple<std::_Mem_fn<void (foedus::thread::ThreadPimpl::*)()> (foedus::thread::ThreadPimpl*)>::operator()() : foedus-core/libfoedus-core.so(_ZNSt12_Bind_simpleIFSt7_Mem_fnIMN6foedus6thread11ThreadPimplEFvvEEPS3_EEclEv+0x1b) [0x7fe512846b69] (libbacktrace: [0x7FE512846B68])
- [12/16] in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (foedus::thread::ThreadPimpl::*)()> (foedus::thread::ThreadPimpl*)> >::_M_run() : foedus-core/libfoedus-core.so(_ZNSt6thread5_ImplISt12_Bind_simpleIFSt7_Mem_fnIMN6foedus6thread11ThreadPimplEFvvEEPS5_EEE6_M_runEv+0x1c) [0x7fe512846b02] (libbacktrace: [0x7FE512846B01])
- [13/16] in ??? : /lib64/libstdc++.so.6(+0xb51e0) [0x7fe5118771e0] (libbacktrace: [0x7FE5118771DF])
- [14/16] in ??? : /lib64/libpthread.so.0(+0x7df5) [0x7fe512166df5] (libbacktrace: [0x7FE512166DF4])
- [15/16] in clone : /lib64/libc.so.6(clone+0x6d) [0x7fe510fdf1ad] (libbacktrace: [0x7FE510FDF1AC])
ycsb_masstree: foedus/storage/masstree/masstree_page_impl.cpp:1300: foedus::ErrorCode foedus::storage::masstree::MasstreeIntermediatePage::adopt_from_child(foedus::thread::Thread*, foedus::storage::masstree::KeySlice, uint8_t, uint8_t, foedus::storage::masstree::MasstreePage*): Assertion `pointer_index == minipage.find_pointer(searching_slice)' failed.

**Comment by hkimura** [comment] 2015-07-31 21:35
Okay, made a debug feature to check 1) bogus write, cases. It's being pushed, and indeed it hits a few bugs. Let's fix them and see if this was caused by them.

**Comment by hkimura** [comment] 2015-07-31 21:39
Enable this option and run it again. I guess you will hit a signal somewhere:
    options.memory_.rigorous_page_boundary_check_ = true;

**Comment by hkimura** [comment] 2015-09-14 18:59
Is this stacktrace same as the one we are still seeing? or that's different one?
If it's a different stacktrace, let's make a new ticket and close this one.

**Comment by wangtzh** [comment] 2015-09-14 19:01
The new one is different, closing this one.

**Closed** 2015-09-14 19:02 UTC
Labels: bug
